Switch to disable gene_names from 'diagram' #629
etal/cnvkit pull request #634
Opened 2021-06-24 11:51 UTC by tetedange13

2021-07-01 22:37 UTC, tskir approved these changes

2021-07-01 22:37 UTC, tskir commented
Thanks Felix, everything looks good to me!

2021-07-06 10:02 UTC, tetedange13 commented
Commit e8470dd218ce4e79d6fc42777d0c741abfbb73e3 should implement a feature discussed [here](https://github.com/etal/cnvkit/issues/628#issuecomment-872768057)
=> Display a single chromosome instead of all
=> I did like `scatter -c`, except "start", "end" are ignored from unpacked range 
=> Works also with `--no-gene-labels`

Kind regards.
Felix.

2021-07-13 22:21 UTC, tskir requested changes

2021-07-13 22:21 UTC, tskir commented on cnvlib/diagram.py
> +        # Better to get them and raise error 'if not None' ??
Thanks for adding this additional feature! — Yes, please check them and raise an error if not None, otherwise the behaviour might be confusing

2021-07-21 06:01 UTC, etal approved these changes
This code LGTM and I approve of the new feature. Without it, the way to get the same effect is by filtering the .cns and/or .cnr, as noted in the comments, to remove chromosomes or replace the gene names with `-`.

The metavar for -c might be better as "LABEL" or "NAME" ( however it appears in other commands) rather than "RANGE" to reduce the temptation to type a basepair-level range.

2021-07-21 12:58 UTC, tetedange13 commented
Hi @etal,

Thanks for your code review ! 
=> I decided to **not set `metavar=` parameter at all**
=> This way this part from `cnvkit.py diagram --help` is pretty self-explanatory:
```python
  -c CHROMOSOME, --chromosome CHROMOSOME
                        Chromosome to display, e.g. 'chr1' (no chromosomal range allowed)
```

Looking good to you?
Have a nice day.
Felix.

2021-07-21 16:32 UTC, etal approved these changes
All LGTM now

2021-07-21 16:32 UTC, merged